import joblib
model=joblib.load("heart.pkl")
age=int(input("enter the age:"))
sex=int(input("enter the sex:"))
cp=int(input("enter the cp:"))
trestbps=int(input("enter the trestbps:"))
chol=int(input("enter the chol:"))
fbs=int(input("enter the fbs:"))
restecg=int(input("enter the restecg:"))
thalach=int(input("enter the thalach:"))
exang=int(input("enter the exang:"))
oldpeak=int(input("enter the oldpeak:"))
slop=int(input("enter the slop:"))
ca=int(input("enter the ca:"))
thal=int(input("enter the thal:"))
print(model.predict([[age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slop,ca,thal]]))